version: '3'
services:
    dev:
        build: '.'
        working_dir: '/app'
        env_file: '.env'
        command: ['dumb-init', 'npm', 'start']
        depends_on:
            - 'rabbit'
            - 'db'
        links:
            - 'rabbit'
            - 'db'
        volumes:
            - './:/app'
    poller:
        build: '.'
        working_dir: '/app'
        env_file: '.env'
        command: ['dumb-init', 'npm', 'run', 'start-poller']
        depends_on:
            - 'rabbit'
            - 'db'
            - 'downloader'
        links:
            - 'rabbit'
            - 'db'
        volumes:
            - './:/app'
    
    cleaner:
        build: '.'
        working_dir: '/app'
        env_file: '.env'
        command: ['dumb-init', 'npm', 'run', 'start-cleaner']
        depends_on:
            - 'rabbit'
            - 'db'
        links:
            - 'rabbit'
            - 'db'
        volumes:
            - './:/app'

    downloader:
        build: '.'
        working_dir: '/app'
        env_file: '.env'
        command: ['dumb-init', 'npm', 'run', 'start-downloader']
        depends_on:
            - 'rabbit'
            - 'db'
            - 'updater'
        links:
            - 'rabbit'
            - 'db'
        volumes:
            - './:/app'

    updater:
        build: '.'
        working_dir: '/app'
        env_file: '.env'
        command: ['dumb-init', 'npm', 'run', 'start-updater']
        depends_on:
            - 'rabbit'
            - 'db'
        links:
            - 'rabbit'
            - 'db'
        volumes:
            - './:/app'

    api:
        build: '.'
        working_dir: '/app'
        env_file: '.env'
        ports:
            - 8080:8080
        command: ['dumb-init', 'npm', 'run', 'start-api']
        depends_on:
            - 'rabbit'
            - 'db'
        links:
            - 'rabbit'
            - 'db'
        volumes:
            - './:/app'

    db:
        image: 'mongo:5.0'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'indexer-mongo'
            MONGO_INITDB_ROOT_PASSWORD: 'indexer-mongo'
        ports:
            - 27017:27017

    rabbit:
        image: 'rabbitmq:3.10.7-management-alpine'
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: 'indexer'
            RABBITMQ_DEFAULT_PASS: 'indexer'
        logging:
            driver: 'none'
        volumes:
            - ./rabbitMQ/definitions.json:/opt/definitions.json:ro
            - ./rabbitMQ/configuration.conf:/etc/rabbitmq/rabbitmq.config:ro

volumes:
  cache:
    driver: local



