version: '3'
services:
    dev:
        build: '.'
        working_dir: '/app'
        env_file: '.env'
        command: ['dumb-init', 'npm', 'start']
        depends_on:
            - 'rabbit'
        links:
            - 'rabbit'
        volumes:
            - './:/app'
    poller:
        build: '.'
        working_dir: '/app'
        env_file: '.env'
        command: ['dumb-init', 'npm', 'start']
        depends_on:
            - 'rabbit'
        links:
            - 'rabbit'
        volumes:
            - './:/app'
    db:
        image: 'mongo:5.0'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'mongouser'
            MONGO_INITDB_ROOT_PASSWORD: 'mongopws'

    rabbit:
        image: 'rabbitmq:3.10.7-management-alpine'
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: 'indexer-rabbit'
            RABBITMQ_DEFAULT_PASS: 'indexer-rabbit'
        logging:
            driver: 'none'
        volumes:
            - ./rabbitMQ/definitions.json:/opt/definitions.json:ro
            - ./rabbitMQ/configuration.conf:/etc/rabbitmq/rabbitmq.config:ro



